name: Page To Makedown
on: 
    issues:
        types: [opened, edited]
jobs:
    Lint:
        # env:
        #     DOCOMMITANDPUSH: false
        runs-on: ubuntu-latest
        steps:
            - name: set env variables
              run: |
                echo "DOCOMMITANDPUSH=false" >> $GITHUB_ENV;
                echo ${{ env.DOCOMMITANDPUSH }}
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '14.16.0'
            - name: false DOCOMMITANDPUSH #echo issue
              run:
                echo "::set-env name=DOCOMMITANDPUSH::true"
                echo ${{ env.DOCOMMITANDPUSH }}
            - name: if
              if: env.DOCOMMITANDPUSH == true
              run: 
                echo "hello" env.DOCOMMITANDPUSH;
                # echo "DOCOMMITANDPUSH=true" >> $GITHUB_ENV;
                # bash ./script/toMarkdown/main.sh "${{github.event.issue.title}}" "${{github.event.issue.body}}";
                # echo "##[set-env DOCOMMITANDPUSH=GOPATH;]true"
                # env.DOCOMMITANDPUSH : true
                # DOCOMMITANDPUSH=true;
