name: Page To Makedown
on: 
    issues:
        types: [opened, edited]
jobs:
    Lint:
        runs-on: ubuntu-latest
        env:
            DOCOMMITANDPUSH: false
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '14.16.0'
            - name: false DOCOMMITANDPUSH #echo issue
              run:
                # bash ./script/toMarkdown/main.sh "${{github.event.issue.title}}" "${{github.event.issue.body}}";
                echo true >> env.DOCOMMITANDPUSH
            - name: if
              if: env.DOCOMMITANDPUSH == true
              run: 
                echo "hello" env.DOCOMMITANDPUSH
