name: Page To Makedown
on: 
    issues:
        types: [opened, edited]
jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '14'
            - name: echo issue
              run:
                issueTitle="${{github.event.issue.title}}";
                issueBody="${{github.event.issue.body}}";
                node script\index.js ${issueTitle};
