name: Page To Makedown
on:
    issues:
        types: [opened, edited]
jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '14.16.0'
            - name: Does the issue need to be converted to markdown
              run: |
                  if [ "${{ github.event.issue.title }}" ] && [ "${{ github.event.issue.body }}" ]; then
                    if [[ "${{ github.event.issue.title }}" =~ ^\[a\]* ]]; then
                      echo "DONEXT=${{ node ./script/test/index.js "${{ github.event.issue.body }}" }}" >> $GITHUB_ENV;
                    else
                      echo "This issue does not need to generate a markdown file."
                      echo "DONEXT=${{ node ./script/test/index.js "${{ github.event.issue.body }}" }}" >> $GITHUB_ENV;
                    fi;
                  else
                    echo "The content or title of the issue is empty."
                    echo "DONEXT=${{ false }}" >> $GITHUB_ENV;
                  fi;
              shell: bash
            # - name: Crawl pages and generate Markdown files
            #   if: env.DONEXT == 'true'
            #   run: |
            #       echo "DONEXT=${{ false }}" >> $GITHUB_ENV;
            #       node ./script/toMarkdown/index.js "${{ github.event.issue.body }}";
            #       echo "DONEXT=${{ true }}" >> $GITHUB_ENV;
            # - name: Git Auto Commit
            #   if: env.DONEXT == 'true'
            #   uses: stefanzweifel/git-auto-commit-action@v4.9.2
            #   with:
            #       commit_message: "${{ github.event.issue.title }}"
            #       file_pattern: chinese/articles/*.md
            #       commit_user_name: PageToMarkdown Bot
            #       commit_user_email: PageToMarkdown-bot@freeCodeCamp.org
            - name: r
              if: env.DONEXT == 'true'
              run: |
                  echo $DONEXT;
